/* CONSTANT BASE_URL // QUALECENCIA NULA ?? // VARIÁVEL DE AMBIETE (import.meta.env.VITE_BACKEND_URL)
// VALOR PADÃO DA VARIÁVEL ("http://127.0.0.1:5173") 
INTERPRETANDO -> PEGA O VALOR DA VARIÁVEL DE AMBIENTE. SE NÃO EXISTIR A VARIAVEL COM ESSE NOME (VITE_BACKEND_URL),
POR PADRÃO UTILIZA O "http://127.0.0.1:5173/" */ 

export const BASE_URL = import.meta.env.VITE_BACKEND_URL ?? "http://127.0.0.1:5173/";
